/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Tragaperras;
import com.sv.udb.clases.Metodos;

import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.Timer;
/**
 *
 * @author Jose Lira
 */
public class FrmTragaperras extends javax.swing.JFrame {

    /**
     * Creates new form FrmTragaperras
     */
    Timer timer;
    int contador;
    String label1,label2,label3;
    private Tragaperras Ejeobje;
    private Metodos obje;
  

    
    
    public FrmTragaperras() {
        initComponents();  
            this.setLocationRelativeTo(null);
         this.Ejeobje=new Tragaperras(); 
         this.obje=new Metodos();
         
          //Se pone fondo al Jframe
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/com/sv/udb/ico/fondo.jpg"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());

                timer = new Timer (500, new ActionListener()
                {
                        @Override
                        public void actionPerformed(ActionEvent e)
                {
                    accionar();
                }
                });           
    
 }
    private void accionar()
    {
         obje=new Metodos();
        ImageIcon icon1 = new ImageIcon(ClassLoader.getSystemResource(obje.imgcrear()));
        lbl17.setIcon(icon1);
        label1 = obje.imgcrear();
        ImageIcon icon2 = new ImageIcon(ClassLoader.getSystemResource(obje.imgcrear()));
         lbl27.setIcon(icon2);        
        label2 = obje.imgcrear();
         ImageIcon icon3 = new ImageIcon(ClassLoader.getSystemResource(obje.imgcrear()));
        lbl37.setIcon(icon3);
       label3 = obje.imgcrear();
                
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl17 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lblempezar = new javax.swing.JLabel();
        lblterminar = new javax.swing.JLabel();
        lblgana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl17.setBackground(new java.awt.Color(255, 204, 204));
        lbl17.setForeground(new java.awt.Color(255, 102, 102));
        lbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/ico/7.png"))); // NOI18N

        lbl37.setBackground(new java.awt.Color(255, 204, 204));
        lbl37.setForeground(new java.awt.Color(255, 102, 102));
        lbl37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/ico/7.png"))); // NOI18N

        lbl27.setBackground(new java.awt.Color(255, 204, 204));
        lbl27.setForeground(new java.awt.Color(255, 102, 102));
        lbl27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/ico/7.png"))); // NOI18N

        lblempezar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblempezar.setForeground(new java.awt.Color(255, 255, 255));
        lblempezar.setText("Empezar");
        lblempezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblempezarMouseClicked(evt);
            }
        });

        lblterminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblterminar.setForeground(new java.awt.Color(255, 255, 255));
        lblterminar.setText("Terminar");
        lblterminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblterminarMouseClicked(evt);
            }
        });

        lblgana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblgana.setForeground(new java.awt.Color(255, 255, 255));
        lblgana.setText("Ganar");
        lblgana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblganaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblgana, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblterminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblempezar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbl27, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl37, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl27)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl17)
                            .addComponent(lbl37))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblempezar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblterminar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgana, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void ga()
    {
         obje=new Metodos();
        ImageIcon icon1 = new ImageIcon(ClassLoader.getSystemResource(obje.gana()));
        lbl17.setIcon(icon1);
        label1 = obje.gana();
        ImageIcon icon2 = new ImageIcon(ClassLoader.getSystemResource(obje.gana()));
         lbl27.setIcon(icon2);        
        label2 = obje.gana();
         ImageIcon icon3 = new ImageIcon(ClassLoader.getSystemResource(obje.gana()));
        lbl37.setIcon(icon3);
       label3 = obje.gana();
        }
   
    private void lblempezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblempezarMouseClicked
        try {
            timer.start();           
        } 
        catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
    }//GEN-LAST:event_lblempezarMouseClicked

    private void lblterminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblterminarMouseClicked
        try {
            timer.stop();
            
            obje= new Metodos();
           if(label1 == label2 && label2==label3)
            {
                JOptionPane.showMessageDialog(this, "Felicidades usted a ganado");
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "A perdido");
            }
        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblterminarMouseClicked

    private void lblganaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblganaMouseClicked
        ga();
          if(label1 == label2 && label2 == label3)
            {
                JOptionPane.showMessageDialog(this, "Felicidades usted a ganado");
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "A perdido");
            }
    }//GEN-LAST:event_lblganaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTragaperras().setVisible(true);
            }
        });
        
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lblempezar;
    private javax.swing.JLabel lblgana;
    private javax.swing.JLabel lblterminar;
    // End of variables declaration//GEN-END:variables
}
